"""
profile/nightly_analyst.py

Two-pass LLM analyst that enriches a UnifiedProfile with:
  Layer 1 — Structured narrative (coach_narrative): multi-section personality
             document written for the AI coach AND developer inspection.
  Layer 2 — LLM-generated plan (suggested_plan): plan items for tomorrow
             grounded in the narrative + today's physiological scores.

Both passes run nightly via jobs/nightly_rebuild.py, sequentially.
Layer 2 reads Layer 1's narrative as its primary input — they share context.

Called with an llm_client that exposes:
    llm_client.chat(system: str, user: str) -> str   (returns raw string)

If llm_client is None (offline/test mode), deterministic fallback narrative
and plan are generated via _fallback_narrative() and _fallback_plan().

Design constraints
------------------
- Layer 1 NEVER reaches raw metric values.  Only scores (0–100) and
  delta strings ("improving", "stable", "declining") enter the prompt.
- Layer 2 output is strict JSON validated by plan_guardrails.py before commit.
- Each narrative section has a fixed header so developers can grep/diff easily.
- The WHAT CHANGED SINCE vN section is generated by diffing current fields
  against previous_narrative stored in UnifiedProfile.
"""

from __future__ import annotations

import json
import logging
import re
from datetime import date, datetime, UTC
from typing import Any, Optional

from profile.profile_schema import (
    AvoidItem,
    UnifiedProfile,
    PlanItem,
)

log = logging.getLogger(__name__)

# ── Prompt constants ───────────────────────────────────────────────────────────

_LAYER1_SYSTEM = """\
You are ZenFlow's internal psychological analyst. Your job is to write a \
structured PERSONALITY SNAPSHOT for a user based on their physiological, \
psychological, behavioural, and engagement data.

OUTPUT RULES
- Use EXACTLY the section headers listed in the user prompt — do not rename them.
- Write in plain, precise English. No fluff. No motivational language.
- Every claim must be grounded in the data provided — if data is absent, write "Insufficient data".
- Cite score numbers (0–100 scale) and counts, not raw physiological values.
- The document is read by developers debugging the system AND by the AI coach at runtime.
- Keep each bullet to 1–2 sentences maximum.
- The WHAT CHANGED SINCE section must list concrete data changes, not impressions.
- The ENGAGEMENT PROFILE section must be honest — if engagement is dropping, say so clearly.
- The WATCH TODAY section must contain 1–3 actionable coach considerations for tomorrow.

COACH WATCH NOTES RULES (the COACH WATCH NOTES section only)
- Write 3–5 bullets. Each bullet is a specific observation the user would recognise about themselves.
- Write in simple Indian English. Short sentences. Maximum 20 words per bullet.
- Sound like a knowledgeable friend, not a clinical system.
- Ground every bullet in a specific data signal in the input — no vague generalisations.
- This section is shown to the user in the app — write for the user, not the developer.
- Examples of good bullets:
    "You haven't worn your band for 4 of the last 7 days — we're missing data."
    "Your stress has been running high since Tuesday — 5 days in a row now."
    "You tend to sleep late and your recovery has been poor most mornings."
    "Stress usually hits you hardest between 9 and 11am on weekdays."
    "Walking has helped your recovery every time you've done it this week."
- If a data point is unavailable, skip that bullet — do not write "Insufficient data" here.
"""

_LAYER2_SYSTEM = """\
You are ZenFlow's daily planning engine. Given a user's personality snapshot and \
their physiological scores for today, output a personalized daily plan.

OUTPUT FORMAT
Output ONLY a valid JSON object with exactly two keys:
  {
    "plan": [...],
    "avoid_items": [...]
  }
No prose, no markdown, no explanation outside the JSON.

PLAN ARRAY RULES
- Each item: {"slug": str, "priority": str, "duration_min": int, "reason": str}
- slug: must be one of the valid slugs listed in the user prompt.
- priority: "must_do" | "recommended" | "optional"
- duration_min: integer, must be within the slug's allowed range.
- reason: 1 sentence in simple Indian English citing the user's specific score or trait.
  Example: "Recovery is at 48 — walking has helped you bounce back before."
- Maximum 1 must_do item if discipline_index < 40.
- Maximum 2 must_do items otherwise.
- If engagement_tier is "at_risk" or "churned", add a short, low-friction item to \
  re-engage the user. Do NOT add hard items that will increase drop-off risk.
- If net_balance < -20 ("red day"), only restorative items — no performance items.
- If mood_baseline is "low" for 5+ days, add a mood-positive item and set tone to gentle.
- Do NOT prescribe social_time if user is introvert AND stress_score > 70.
- The reason field MUST reference a specific score, trait, or fact from the snapshot.

AVOID ITEMS ARRAY RULES
- Maximum 3 items. Can be empty [].
- Each item: {"slug_or_label": str, "reason": str}
- slug_or_label: a plain activity name e.g. "hard gym session", "late night", "alcohol"
- reason: 1 sentence in simple Indian English citing the specific data that drives this.
  Example: "Recovery is at 38 — pushing hard will make tomorrow worse."
- Only flag things genuinely counter-indicated by the data. Do not add avoid items on green days.
- Reason MUST cite a specific number or trend — never write generic advice.
"""


# ── Public API ────────────────────────────────────────────────────────────────

def run_layer1_narrative(
    profile: UnifiedProfile,
    *,
    llm_client: Optional[Any] = None,
    today: Optional[date] = None,
) -> UnifiedProfile:
    """
    Layer 1: Generate the structured narrative and attach to profile.
    Returns the same UnifiedProfile with coach_narrative populated.
    """
    today = today or date.today()

    if llm_client is None:
        profile.coach_narrative = _fallback_narrative(profile, today)
        return profile

    user_prompt = _build_layer1_user_prompt(profile, today)
    try:
        raw = llm_client.chat(_LAYER1_SYSTEM, user_prompt)
        profile.coach_narrative = raw.strip()
    except Exception:
        log.exception("Layer 1 LLM call failed — using fallback narrative")
        profile.coach_narrative = _fallback_narrative(profile, today)

    return profile


def run_layer2_plan(
    profile: UnifiedProfile,
    *,
    llm_client: Optional[Any] = None,
    net_balance: Optional[float] = None,
    stress_score: Optional[int] = None,
    recovery_score: Optional[int] = None,
    available_slugs: Optional[list[str]] = None,
    today: Optional[date] = None,
    adherence: Optional[dict] = None,
    assessment_note: Optional[str] = None,
) -> UnifiedProfile:
    """
    Layer 2: Generate the suggested plan and attach to profile.
    Returns the same UnifiedProfile with suggested_plan populated.

    The plan is validated by plan_guardrails.py before being committed
    to daily_plans — this function only populates suggested_plan.
    """
    today = today or date.today()
    profile.plan_for_date = today

    if llm_client is None:
        profile.suggested_plan = _fallback_plan(profile, net_balance)
        profile.avoid_items = []
        return profile

    user_prompt = _build_layer2_user_prompt(
        profile,
        net_balance=net_balance,
        stress_score=stress_score,
        recovery_score=recovery_score,
        available_slugs=available_slugs or [],
        today=today,
        adherence=adherence,
        assessment_note=assessment_note,
    )

    plan_items: list[PlanItem] = []
    avoid_items: list[AvoidItem] = []
    for attempt in range(2):
        try:
            raw = llm_client.chat(_LAYER2_SYSTEM, user_prompt)
            plan_items, avoid_items = _parse_plan_json(raw)
            if plan_items:
                break
        except Exception:
            log.exception("Layer 2 LLM call attempt %d failed", attempt + 1)

    if not plan_items:
        plan_items = _fallback_plan(profile, net_balance)
        profile.plan_guardrail_notes.append("layer2_fallback: LLM unavailable")

    profile.suggested_plan = plan_items
    profile.avoid_items = avoid_items
    return profile


# ── Prompt builders ───────────────────────────────────────────────────────────

def _build_layer1_user_prompt(profile: UnifiedProfile, today: date) -> str:
    p  = profile.physio
    ps = profile.psych
    b  = profile.behaviour
    e  = profile.engagement
    cr = profile.coach_rel
    v  = profile.narrative_version

    # Format top triggers
    triggers_str = "None identified yet"
    if ps.top_anxiety_triggers:
        triggers_str = "; ".join(
            f"{t.get('type','?')} ({t.get('count',0)}x, strength {t.get('strength',0):.2f})"
            for t in ps.top_anxiety_triggers[:5]
        )

    # Format top calming activities
    calming_str = "Insufficient data"
    if b.top_calming_activities:
        calming_str = ", ".join(
            f"{a.get('slug','?')} (avg +{a.get('avg_score_delta',0):.1f} pts, {a.get('count',0)}x)"
            for a in b.top_calming_activities[:3]
        )

    stressing_str = "Insufficient data"
    if b.top_stress_activities:
        stressing_str = ", ".join(
            f"{a.get('slug','?')} (avg -{abs(a.get('avg_score_delta',0)):.1f} pts, {a.get('count',0)}x)"
            for a in b.top_stress_activities[:3]
        )

    # Format facts
    facts_str = "None extracted yet"
    if profile.facts:
        confirmed  = [f for f in profile.facts if f.user_confirmed or f.confidence >= 0.7]
        tentative  = [f for f in profile.facts if not f.user_confirmed and f.confidence < 0.7]
        lines = []
        for f in confirmed[:6]:
            lines.append(f"  [confirmed] {f.fact_text}")
        for f in tentative[:4]:
            lines.append(f"  [tentative, conf={f.confidence:.2f}] {f.fact_text}")
        facts_str = "\n".join(lines) if lines else "None extracted yet"

    # Previous narrative for delta generation
    prev = profile.previous_narrative or "(no previous narrative — this is version 1)"
    prev_excerpt = prev[:800] if len(prev) > 800 else prev

    discipline_str = f"{ps.discipline_index:.0f}/100" if ps.discipline_index is not None else "Insufficient data"
    anxiety_str    = f"{ps.anxiety_sensitivity:.2f}" if ps.anxiety_sensitivity is not None else "Insufficient data"
    intero_str     = f"r={ps.interoception_alignment:.2f}" if ps.interoception_alignment is not None else "Insufficient data"
    sleep_str      = f"{p.sleep_recovery_efficiency:.2f}" if p.sleep_recovery_efficiency is not None else "Unknown"

    # Engagement detail
    nudge_str = f"{e.nudge_response_rate_30d:.0%}" if e.nudge_response_rate_30d is not None else "Unknown"
    band_str  = (
        f"{e.band_days_worn_last7}/7 days last week, {e.band_days_worn_last30}/30 days last month"
        if e.band_days_worn_last7 is not None else "Unknown"
    )
    mr_str = (
        f"{e.morning_read_rate_30d:.0%} of days (30d), streak {e.morning_read_streak} days"
        if e.morning_read_rate_30d is not None else "Unknown"
    )

    return f"""
Write a PERSONALITY SNAPSHOT for version v{v} dated {today.isoformat()}.
Use EXACTLY these section headers. Follow them strictly.

==============================================================
DATA INPUT
==============================================================

USER IDENTITY
  Archetype: {profile.archetype_primary or 'Unknown'} / {profile.archetype_secondary or 'Unknown'}
  Training level: {profile.training_level}
  Days active: {profile.days_active}

PHYSIOLOGICAL TRAITS
  PRF: {p.prf_bpm or 'Not found'} bpm ({p.prf_status or 'PRF_UNKNOWN'})
  Coherence trainability: {p.coherence_trainability or 'Unknown'}
  Recovery arc speed: {p.recovery_arc_speed or 'Unknown'}
  Stress peak pattern: {p.stress_peak_pattern or 'Unknown'}
  Sleep recovery efficiency: {sleep_str}

PSYCHOLOGICAL TRAITS
  Social energy type: {ps.social_energy_type or 'Unknown'}
  Anxiety sensitivity: {anxiety_str} (0=none, 1=extreme)
  Top anxiety triggers: {triggers_str}
  Primary recovery style: {ps.primary_recovery_style or 'Unknown'}
  Discipline index: {discipline_str}
  Current streak: {ps.streak_current} days
  Mood baseline (14d): {ps.mood_baseline or 'Unknown'}
  Interoception alignment: {intero_str}

BEHAVIOURAL PATTERNS
  Top calming activities: {calming_str}
  Top stressing activities: {stressing_str}
  Movement enjoyed: {', '.join(b.movement_enjoyed) or 'Not specified'}
  Decompresses via: {', '.join(b.decompress_via) or 'Not specified'}
  Alcohol: {b.alcohol or 'Not specified'}
  Sleep schedule: {b.sleep_schedule or 'Not specified'}

ENGAGEMENT DATA
  Band wear: {band_str}
  Morning reads: {mr_str}
  ZenFlow sessions last 7 days: {e.sessions_last7}
  ZenFlow sessions last 30 days: {e.sessions_last30}
  Conversations last 7 days: {e.conversations_last7}
  Nudge response rate (30d): {nudge_str}
  Days since last app interaction: {e.last_app_interaction_days if e.last_app_interaction_days is not None else 'Unknown'}
  Engagement tier: {e.engagement_tier or 'Unknown'}
  Engagement trend: {e.engagement_trend or 'Unknown'}

CONVERSATION FACTS (extracted from chat history)
{facts_str}

COACH RELATIONSHIP
  Preferred tone: {cr.preferred_tone or 'Unknown'}
  Nudge response rate (all time): {f"{cr.nudge_response_rate:.0%}" if cr.nudge_response_rate is not None else "Unknown"}
  Best nudge window: {cr.best_nudge_window or 'Unknown'}
  Last insight delivered: {cr.last_insight_delivered or 'None'}

PREVIOUS NARRATIVE (v{v - 1}):
{prev_excerpt}

==============================================================
REQUIRED OUTPUT FORMAT — use EXACTLY these headers, in order:
==============================================================

PERSONALITY SNAPSHOT  [v{v} — {today.isoformat()}]

PHYSIOLOGICAL TRAITS
  (bullet points about PRF, coherence, recovery arc, stress peaks, sleep efficiency)

PSYCHOLOGICAL TRAITS
  (bullet points about social type, anxiety sensitivity/triggers, discipline, mood, interoception)

BEHAVIOURAL PATTERNS
  (bullet points about calming/stressing activities, movement, decompression, habits)

ENGAGEMENT PROFILE
  (bullet points about band wear, morning reads, sessions, nudges, engagement tier, trend)
  (be honest — if declining, state it and the pattern)
  (include what would re-engage this user based on their profile)

CONVERSATION FACTS
  (list confirmed facts first, tentative below — mark each [confirmed] or [tentative])
  (if none: write "No facts extracted yet.")

COACH RELATIONSHIP
  (preferred tone, nudge window, response rate, one line on what works for this user)

WHAT CHANGED SINCE v{v - 1} ({today.isoformat()})
  (bullet point each concrete data change — metric shifts, new facts, tier changes)
  (if v1: write "First profile build.")

WATCH TODAY
  (1–3 specific actionable considerations for the coach tomorrow, grounded in the data)
  (use score language: readiness/stress/recovery 0–100)

COACH WATCH NOTES
  (3–5 bullets, plain Indian English, max 20 words each)
  (each bullet is grounded in a specific data signal above — no vague generalisations)
  (this section surfaces in the app — write for the user, not the developer)
""".strip()


def _build_layer2_user_prompt(
    profile: UnifiedProfile,
    *,
    net_balance: Optional[float],
    stress_score: Optional[int],
    recovery_score: Optional[int],
    available_slugs: list[str],
    today: date,
    adherence: Optional[dict] = None,
    assessment_note: Optional[str] = None,
) -> str:
    narrative = profile.coach_narrative or "(narrative unavailable)"
    slugs_str = ", ".join(available_slugs) if available_slugs else "walking, breathing, stretching, book_reading, nap"

    nb_str = f"{net_balance:+.1f}" if net_balance is not None else "Unknown"

    adherence_section = ""
    if adherence:
        lines = "\n".join(
            f"  {cat}: {round(pct * 100)}%"
            for cat, pct in sorted(adherence.items())
        )
        adherence_section = f"\nADHERENCE LAST 7 DAYS (by category):\n{lines}"
    if assessment_note:
        adherence_section += f"\nCOACHING NOTE: {assessment_note}"

    return f"""
TODAY: {today.isoformat()}
NET BALANCE: {nb_str} (positive = surplus, negative = debt; drives day colour)
STRESS SCORE: {stress_score if stress_score is not None else 'Unknown'}/100
WAKING RECOVERY SCORE: {recovery_score if recovery_score is not None else 'Unknown'}/100{adherence_section}

USER PERSONALITY SNAPSHOT:
{narrative}

VALID ACTIVITY SLUGS (use ONLY these):
{slugs_str}

ENGAGEMENT NOTE:
Engagement tier is: {profile.engagement.engagement_tier or 'Unknown'}.
If "at_risk" or "churned", prioritize 1 easy win to rebuild the habit — do not overwhelm.

Generate the plan now. Output only valid JSON array. No prose.
""".strip()


# ── JSON parser ───────────────────────────────────────────────────────────────

def _parse_plan_json(raw: str) -> tuple[list[PlanItem], list[AvoidItem]]:
    """Extract and parse the JSON from a Layer 2 LLM response.

    Accepts two formats:
      New: {"plan": [...], "avoid_items": [...]}
      Legacy (backward-compat): bare JSON array [...]
    """
    # Strip markdown code fences if present
    cleaned = re.sub(r"```(?:json)?", "", raw).strip().strip("`").strip()

    # Try new object format first
    obj_match = re.search(r"\{.*\}", cleaned, re.DOTALL)
    raw_plan: list[dict] = []
    raw_avoid: list[dict] = []

    if obj_match:
        try:
            obj = json.loads(obj_match.group(0))
            if isinstance(obj, dict) and "plan" in obj:
                raw_plan  = obj.get("plan", []) or []
                raw_avoid = obj.get("avoid_items", []) or []
            elif isinstance(obj, dict):
                # Unexpected object shape — fall through to array search
                obj = None
        except json.JSONDecodeError:
            obj = None
    else:
        obj = None

    if obj is None:
        # Backward compat: bare array
        arr_match = re.search(r"\[.*\]", cleaned, re.DOTALL)
        if not arr_match:
            log.warning("Layer 2: no JSON found in LLM output")
            return [], []
        try:
            raw_plan = json.loads(arr_match.group(0))
        except json.JSONDecodeError as exc:
            log.warning("Layer 2: JSON parse error: %s", exc)
            return [], []

    plan_items: list[PlanItem] = []
    for item in raw_plan:
        if not isinstance(item, dict):
            continue
        slug     = item.get("slug", "")
        priority = item.get("priority", "recommended")
        duration = item.get("duration_min", 15)
        reason   = item.get("reason", "")
        if not slug:
            continue
        if priority not in ("must_do", "recommended", "optional"):
            priority = "recommended"
        try:
            duration = int(duration)
        except (ValueError, TypeError):
            duration = 15
        plan_items.append(PlanItem(
            slug=slug,
            priority=priority,
            duration_min=duration,
            reason=str(reason)[:300],
        ))

    avoid_items: list[AvoidItem] = []
    for item in raw_avoid[:3]:  # hard cap at 3
        if not isinstance(item, dict):
            continue
        label  = item.get("slug_or_label", "")
        reason = item.get("reason", "")
        if not label:
            continue
        avoid_items.append(AvoidItem(
            slug_or_label=str(label)[:100],
            reason=str(reason)[:300],
        ))

    return plan_items, avoid_items


# ── Fallback generators (no LLM) ─────────────────────────────────────────────

def _fallback_narrative(profile: UnifiedProfile, today: date) -> str:
    """Deterministic narrative for offline/test mode."""
    e  = profile.engagement
    ps = profile.psych
    p  = profile.physio

    archetype_line = f"{profile.archetype_primary or 'Unknown'}" + (
        f" / {profile.archetype_secondary}" if profile.archetype_secondary else ""
    )

    discipline_line = f"{ps.discipline_index:.0f}/100" if ps.discipline_index is not None else "Insufficient data"
    social_line = ps.social_energy_type or "unknown"
    anxiety_line = f"{ps.anxiety_sensitivity:.2f}" if ps.anxiety_sensitivity is not None else "Insufficient data"
    prf_line = f"{p.prf_bpm} bpm ({p.prf_status})" if p.prf_bpm else "Not yet found"

    return f"""PERSONALITY SNAPSHOT  [v{profile.narrative_version} — {today.isoformat()}]

PHYSIOLOGICAL TRAITS
  PRF: {prf_line}.
  Coherence trainability: {p.coherence_trainability or 'Unknown'}.
  Recovery arc speed: {p.recovery_arc_speed or 'Unknown'}.
  Stress peak: {p.stress_peak_pattern or 'Unknown'}.
  Sleep efficiency: {p.sleep_recovery_efficiency or 'Unknown'}.

PSYCHOLOGICAL TRAITS
  Social energy: {social_line}. Anxiety sensitivity: {anxiety_line}.
  Discipline index: {discipline_line}. Streak: {ps.streak_current} days.
  Mood baseline: {ps.mood_baseline or 'Unknown'}.
  Interoception alignment: {ps.interoception_alignment or 'Unknown'}.

BEHAVIOURAL PATTERNS
  Calming activities: {', '.join(a.get('slug','?') for a in profile.behaviour.top_calming_activities[:3]) or 'Insufficient data'}.
  Stressing activities: {', '.join(a.get('slug','?') for a in profile.behaviour.top_stress_activities[:3]) or 'Insufficient data'}.
  Primary recovery style: {ps.primary_recovery_style or 'Unknown'}.

ENGAGEMENT PROFILE
  Engagement tier: {e.engagement_tier or 'Unknown'}. Trend: {e.engagement_trend or 'Unknown'}.
  Sessions last 7 days: {e.sessions_last7}. Conversations last 7 days: {e.conversations_last7}.
  Morning read rate (30d): {f"{e.morning_read_rate_30d:.0%}" if e.morning_read_rate_30d is not None else 'Unknown'}.
  Band wear last 7 days: {e.band_days_worn_last7 if e.band_days_worn_last7 is not None else 'Unknown'}/7.
  Nudge response rate (30d): {f"{e.nudge_response_rate_30d:.0%}" if e.nudge_response_rate_30d is not None else 'Unknown'}.

CONVERSATION FACTS
  No facts extracted yet.

COACH RELATIONSHIP
  Preferred tone: {profile.coach_rel.preferred_tone or 'Unknown'}.
  Best nudge window: {profile.coach_rel.best_nudge_window or 'Unknown'}.

WHAT CHANGED SINCE v{profile.narrative_version - 1} ({today.isoformat()})
  {"First profile build." if profile.narrative_version <= 1 else "Incremental rebuild."}

WATCH TODAY
  Archetype: {archetype_line}. Training level: {profile.training_level}.
  Data confidence: {profile.data_confidence:.0%} — build more data for sharper coaching.

COACH WATCH NOTES
  • Keep it going — {profile.training_level} training level looks steady.
  • Data confidence is at {profile.data_confidence:.0%} — more consistent band wear will sharpen your plan.
  • Engagement: {e.engagement_tier or 'building'} — one session a day keeps the habit alive.
""".strip()


def _fallback_plan(
    profile: UnifiedProfile,
    net_balance: Optional[float],
) -> list[PlanItem]:
    """
    Deterministic fallback plan when LLM is unavailable.
    Based on net_balance: ≥10 = green, ≥-20 = yellow, else rest.
    """
    nb = net_balance if net_balance is not None else 0.0

    items: list[PlanItem] = []

    if nb >= 10.0:
        items.append(PlanItem(
            slug="breathing",
            priority="must_do",
            duration_min=10,
            reason="Green balance — establish morning anchor with a short breathing session.",
        ))
        items.append(PlanItem(
            slug="walking",
            priority="recommended",
            duration_min=20,
            reason="Positive balance — daytime walk supports recovery.",
        ))
    elif nb >= -20.0:
        items.append(PlanItem(
            slug="breathing",
            priority="must_do",
            duration_min=10,
            reason="Yellow balance — one grounding session is the priority.",
        ))
        items.append(PlanItem(
            slug="stretching",
            priority="optional",
            duration_min=10,
            reason="Light movement on a moderate-balance day.",
        ))
    else:
        items.append(PlanItem(
            slug="breathing",
            priority="must_do",
            duration_min=5,
            reason="Negative balance — keep it minimal. 5-minute breathing only.",
        ))

    return items
