"""
coach/memory_store.py

Conversation state persistence for the coach live conversation mode.

Design
------
ConversationState is the rolling memory that keeps a conversation coherent
across turns without passing full history to the LLM.

After turn 3, the full turn history is replaced by a 300-word rolling summary
generated by conversation.py. This prevents context blowout for long sessions.

The safety_triggered flag latches permanently — once set True it never resets.
The API layer checks this flag before every call.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


# ── ConversationState dataclass ───────────────────────────────────────────────

@dataclass
class ConversationState:
    """
    Rolling conversation memory for a single coaching session.

    Fields
    ------
    conversation_id
        UUID assigned at session start.
    user_id
        Opaque user identifier — not exposed to LLM.
    turn_index
        Zero-based count of completed turns.
    started_at
        UTC timestamp of session open.
    trigger_context
        The trigger_type that opened this conversation (e.g. "morning_brief").
    rolling_summary
        Condensed history, max 300 words. Replaces full history after turn 3.
    accumulated_signals
        Plain-English signals extracted from the conversation by conversation_extractor.
        These feed back into HabitSignal tables at close.
    plan_delta_net
        Running tally of prescription changes proposed during this conversation.
    safety_triggered
        Once True, latches permanently. Causes immediate handoff message.
    """
    conversation_id:    str
    user_id:            str
    turn_index:         int      = 0
    started_at:         datetime = field(default_factory=datetime.utcnow)
    trigger_context:    str      = ""
    rolling_summary:    str      = ""
    accumulated_signals: list[str]  = field(default_factory=list)
    accumulated_facts:   list[dict] = field(default_factory=list)  # raw fact dicts from fact_extractor
    plan_delta_net:     dict       = field(default_factory=dict)
    safety_triggered:   bool       = False


# ── MemoryStore ───────────────────────────────────────────────────────────────

class MemoryStore:
    """
    In-memory store for active conversation states.

    For production, replace the backing dict with a Redis or SQLite store.
    The interface stays identical.
    """

    def __init__(self) -> None:
        self._store: dict[str, ConversationState] = {}

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    def create_session(
        self,
        user_id: str,
        trigger_context: str = "",
    ) -> ConversationState:
        """Open a new conversation session and return its state object."""
        cid = str(uuid.uuid4())
        state = ConversationState(
            conversation_id  = cid,
            user_id          = user_id,
            trigger_context  = trigger_context,
        )
        self._store[cid] = state
        return state

    def get(self, conversation_id: str) -> Optional[ConversationState]:
        """Retrieve an active session by ID."""
        return self._store.get(conversation_id)

    def save(self, state: ConversationState) -> None:
        """Persist updated state."""
        self._store[state.conversation_id] = state

    def close_session(self, conversation_id: str) -> Optional[ConversationState]:
        """Close and remove a session. Returns the final state for archiving."""
        return self._store.pop(conversation_id, None)

    # ── Mutation helpers (called by conversation.py) ──────────────────────────

    def advance_turn(self, conversation_id: str) -> Optional[ConversationState]:
        """Increment turn_index and return the updated state."""
        state = self._store.get(conversation_id)
        if state is None:
            return None
        state.turn_index += 1
        return state

    def update_summary(self, conversation_id: str, summary: str) -> None:
        """Replace rolling_summary with new condensed text."""
        state = self._store.get(conversation_id)
        if state:
            state.rolling_summary = summary

    def add_signal(self, conversation_id: str, signal: str) -> None:
        """Add an extracted signal string to accumulated_signals."""
        state = self._store.get(conversation_id)
        if state:
            state.accumulated_signals.append(signal)

    def add_facts(self, conversation_id: str, facts: list[dict]) -> None:
        """Append extracted fact dicts to accumulated_facts."""
        if not facts:
            return
        state = self._store.get(conversation_id)
        if state:
            state.accumulated_facts.extend(facts)

    def latch_safety(self, conversation_id: str) -> None:
        """
        Permanently set safety_triggered = True.

        This is a one-way operation. There is no unlock.
        The session should be closed immediately after calling this.
        """
        state = self._store.get(conversation_id)
        if state:
            state.safety_triggered = True
