"""initial schema — all tables

Revision ID: 0001
Revises:
Create Date: 2026-03-10 00:00:00.000000

Hand-written from api/db/schema.py  — covers every table in the initial
design.  Generated by inspecting Base.metadata rather than running
autogenerate against a live DB, so it is safe to apply to a blank schema.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── users ─────────────────────────────────────────────────────────────────
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("email", sa.String(255), unique=True, nullable=True),
        sa.Column("onboarding", sa.JSON, nullable=True),
        sa.Column("archetype_primary", sa.String(40), nullable=True),
        sa.Column("archetype_secondary", sa.String(40), nullable=True),
        sa.Column("archetype_confidence", sa.JSON, nullable=True),
        sa.Column("archetype_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("training_level", sa.Integer, nullable=True, server_default="1"),
        sa.Column("level_updated_at", sa.DateTime(timezone=True), nullable=True),
    )

    # ── sessions ──────────────────────────────────────────────────────────────
    op.create_table(
        "sessions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("context", sa.String(30), nullable=False, server_default="session"),
        sa.Column("practice_type", sa.String(40), nullable=True),
        sa.Column("session_score", sa.Float, nullable=True),
        sa.Column("coherence_avg", sa.Float, nullable=True),
        sa.Column("zone_1_seconds", sa.Float, nullable=True),
        sa.Column("zone_2_seconds", sa.Float, nullable=True),
        sa.Column("zone_3_seconds", sa.Float, nullable=True),
        sa.Column("zone_4_seconds", sa.Float, nullable=True),
        sa.Column("rmssd_pre", sa.Float, nullable=True),
        sa.Column("rmssd_post", sa.Float, nullable=True),
        sa.Column("pi_pre", sa.Float, nullable=True),
        sa.Column("pi_post", sa.Float, nullable=True),
        sa.Column("is_hardmode", sa.Boolean, nullable=True, server_default="false"),
        sa.Column("config_version", sa.Integer, nullable=False, server_default="1"),
    )

    # ── metrics ───────────────────────────────────────────────────────────────
    op.create_table(
        "metrics",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "session_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("sessions.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sa.String(40), nullable=False),
        sa.Column("value", sa.Float, nullable=False),
        sa.Column("confidence", sa.Float, nullable=False),
        sa.Column("context", sa.String(30), nullable=False),
    )
    op.create_index("ix_metrics_user_ts", "metrics", ["user_id", "ts"])
    op.create_index("ix_metrics_user_name_ts", "metrics", ["user_id", "name", "ts"])

    # ── personal_models ───────────────────────────────────────────────────────
    op.create_table(
        "personal_models",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            unique=True,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer, nullable=True, server_default="1"),
        # RMSSD distribution
        sa.Column("rmssd_floor", sa.Float, nullable=True),
        sa.Column("rmssd_ceiling", sa.Float, nullable=True),
        sa.Column("rmssd_weekday_avg", sa.Float, nullable=True),
        sa.Column("rmssd_weekend_avg", sa.Float, nullable=True),
        sa.Column("rmssd_morning_avg", sa.Float, nullable=True),
        # Recovery arc
        sa.Column("recovery_arc_mean_hours", sa.Float, nullable=True),
        sa.Column("recovery_arc_fast_hours", sa.Float, nullable=True),
        sa.Column("recovery_arc_slow_hours", sa.Float, nullable=True),
        # Coherence trainability
        sa.Column("coherence_floor", sa.Float, nullable=True),
        sa.Column("coherence_trainability", sa.String(20), nullable=True),
        # Stress fingerprint
        sa.Column("stress_peak_day", sa.String(12), nullable=True),
        sa.Column("stress_peak_hour", sa.Integer, nullable=True),
        # Compliance
        sa.Column("compliance_best_window", sa.String(5), nullable=True),
        # Interoception
        sa.Column("interoception_gap", sa.Float, nullable=True),
        # RSA trainability
        sa.Column("rsa_resting_avg", sa.Float, nullable=True),
        sa.Column("rsa_guided_avg", sa.Float, nullable=True),
        sa.Column("rsa_trainability_delta", sa.Float, nullable=True),
        sa.Column("rsa_trainability", sa.String(20), nullable=True),
        # Sleep proxy
        sa.Column("sleep_recovery_efficiency", sa.Float, nullable=True),
        sa.Column("overnight_rmssd_delta_avg", sa.Float, nullable=True),
        # Activity × coherence map
        sa.Column("natural_elevators", sa.JSON, nullable=True),
        sa.Column("coherence_drains", sa.JSON, nullable=True),
        sa.Column("best_natural_window_start", sa.String(5), nullable=True),
        sa.Column("worst_natural_window_start", sa.String(5), nullable=True),
        # LF/HF
        sa.Column("lf_hf_resting", sa.Float, nullable=True),
        sa.Column("lf_hf_sleep", sa.Float, nullable=True),
        # Stress capacity baseline
        sa.Column("stress_capacity_floor_rmssd", sa.Float, nullable=True),
        sa.Column("capacity_version", sa.Integer, nullable=True, server_default="0"),
        # Chronotype
        sa.Column("typical_wake_time", sa.String(5), nullable=True),
        sa.Column("typical_sleep_time", sa.String(5), nullable=True),
        # Full fingerprint blob
        sa.Column("fingerprint_json", sa.JSON, nullable=True),
        # PRF
        sa.Column("prf_bpm", sa.Float, nullable=True),
        sa.Column("prf_status", sa.String(20), nullable=True, server_default="PRF_UNKNOWN"),
    )

    # ── model_snapshots ───────────────────────────────────────────────────────
    op.create_table(
        "model_snapshots",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "snapshot_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("model_version", sa.Integer, nullable=False),
        sa.Column("snapshot_json", sa.JSON, nullable=False),
    )

    # ── user_habits ───────────────────────────────────────────────────────────
    op.create_table(
        "user_habits",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            unique=True,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("movement_enjoyed", sa.JSON, nullable=True),
        sa.Column("exercise_frequency", sa.String(30), nullable=True),
        sa.Column("alcohol", sa.String(30), nullable=True),
        sa.Column("caffeine", sa.String(30), nullable=True),
        sa.Column("smoking", sa.String(20), nullable=True),
        sa.Column("sleep_schedule", sa.String(20), nullable=True),
        sa.Column("typical_day", sa.String(40), nullable=True),
        sa.Column("stress_drivers", sa.JSON, nullable=True),
        sa.Column("decompress_via", sa.JSON, nullable=True),
    )

    # ── habit_events ──────────────────────────────────────────────────────────
    op.create_table(
        "habit_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_type", sa.String(40), nullable=False),
        sa.Column("severity", sa.String(20), nullable=True),
        sa.Column("source", sa.String(20), nullable=False),
        sa.Column("notes", sa.Text, nullable=True),
        sa.Column("rmssd_delta_next_morning", sa.Float, nullable=True),
    )
    op.create_index("ix_habit_events_user_ts", "habit_events", ["user_id", "ts"])

    # ── activity_coherence_events ─────────────────────────────────────────────
    op.create_table(
        "activity_coherence_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activity_tag", sa.String(40), nullable=False),
        sa.Column("activity_label", sa.String(100), nullable=True),
        sa.Column("coherence", sa.Float, nullable=False),
        sa.Column("duration_minutes", sa.Float, nullable=True),
        sa.Column("confidence", sa.Float, nullable=False),
        sa.Column("source", sa.String(30), nullable=False),
        sa.Column("notes", sa.Text, nullable=True),
    )
    op.create_index(
        "ix_activity_coherence_user_ts", "activity_coherence_events", ["user_id", "ts"]
    )
    op.create_index(
        "ix_activity_coherence_user_tag",
        "activity_coherence_events",
        ["user_id", "activity_tag"],
    )

    # ── morning_reads ─────────────────────────────────────────────────────────
    op.create_table(
        "morning_reads",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("read_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("rmssd_ms", sa.Float, nullable=True),
        sa.Column("rsa_power", sa.Float, nullable=True),
        sa.Column("coherence", sa.Float, nullable=True),
        sa.Column("lf_hf", sa.Float, nullable=True),
        sa.Column("hr_bpm", sa.Float, nullable=True),
        sa.Column("confidence", sa.Float, nullable=False, server_default="0.0"),
        sa.Column("day_type", sa.String(10), nullable=True),
        sa.Column("vs_personal_avg_pct", sa.Float, nullable=True),
        sa.Column("config_version", sa.Integer, nullable=False, server_default="1"),
    )
    op.create_index(
        "ix_morning_reads_user_date", "morning_reads", ["user_id", "read_date"]
    )

    # ── check_ins ─────────────────────────────────────────────────────────────
    op.create_table(
        "check_ins",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reactivity", sa.Integer, nullable=False),
        sa.Column("focus", sa.Integer, nullable=False),
        sa.Column("recovery", sa.Integer, nullable=False),
        sa.Column("rmssd_same_day", sa.Float, nullable=True),
    )

    # ── coach_messages ────────────────────────────────────────────────────────
    op.create_table(
        "coach_messages",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("message_type", sa.String(30), nullable=False),
        sa.Column("summary", sa.Text, nullable=False),
        sa.Column("reason", sa.Text, nullable=True),
        sa.Column("action", sa.Text, nullable=True),
        sa.Column("encouragement", sa.Text, nullable=True),
        sa.Column("tone", sa.String(20), nullable=True),
        sa.Column("user_reaction", sa.String(20), nullable=True),
    )

    # ── conversation_events ───────────────────────────────────────────────────
    op.create_table(
        "conversation_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "ts",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("role", sa.String(10), nullable=False),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("extracted_events", sa.JSON, nullable=True),
        sa.Column("plan_adjusted", sa.Boolean, nullable=True, server_default="false"),
    )

    # ── weekly_outcomes ───────────────────────────────────────────────────────
    op.create_table(
        "weekly_outcomes",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("week_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("config_version", sa.Integer, nullable=False),
        sa.Column("resilience_avg", sa.Float, nullable=True),
        sa.Column("resilience_delta", sa.Float, nullable=True),
        sa.Column("recovery_arc_avg_hours", sa.Float, nullable=True),
        sa.Column("recovery_arc_delta", sa.Float, nullable=True),
        sa.Column("sessions_completed", sa.Integer, nullable=True),
        sa.Column("sessions_planned", sa.Integer, nullable=True),
        sa.Column("zone3_total_minutes", sa.Float, nullable=True),
        sa.Column("hardmode_sessions", sa.Integer, nullable=True),
        sa.Column("report_json", sa.JSON, nullable=True),
    )

    # ── monthly_outcomes ──────────────────────────────────────────────────────
    op.create_table(
        "monthly_outcomes",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("month_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("config_version", sa.Integer, nullable=False),
        sa.Column("resilience_vs_baseline", sa.Float, nullable=True),
        sa.Column("recovery_arc_vs_baseline", sa.Float, nullable=True),
        sa.Column("sleep_quality_vs_baseline", sa.Float, nullable=True),
        sa.Column("coherence_vs_baseline", sa.Float, nullable=True),
        sa.Column("interoception_correlation", sa.Float, nullable=True),
        sa.Column("archetype_at_start", sa.String(40), nullable=True),
        sa.Column("archetype_at_end", sa.String(40), nullable=True),
        sa.Column("report_json", sa.JSON, nullable=True),
    )

    # ── background_windows ────────────────────────────────────────────────────
    op.create_table(
        "background_windows",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("context", sa.String(20), nullable=False, server_default="background"),
        sa.Column("rmssd_ms", sa.Float, nullable=True),
        sa.Column("hr_bpm", sa.Float, nullable=True),
        sa.Column("lf_hf", sa.Float, nullable=True),
        sa.Column("confidence", sa.Float, nullable=False, server_default="0.0"),
        sa.Column("acc_mean", sa.Float, nullable=True),
        sa.Column("gyro_mean", sa.Float, nullable=True),
        sa.Column("n_beats", sa.Integer, nullable=False, server_default="0"),
        sa.Column("artifact_rate", sa.Float, nullable=False, server_default="0.0"),
        sa.Column("is_valid", sa.Boolean, nullable=False, server_default="false"),
    )
    op.create_index(
        "ix_bg_windows_user_start", "background_windows", ["user_id", "window_start"]
    )
    op.create_index(
        "ix_bg_windows_user_context", "background_windows", ["user_id", "context"]
    )

    # ── stress_windows ────────────────────────────────────────────────────────
    op.create_table(
        "stress_windows",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Float, nullable=False),
        sa.Column("rmssd_min_ms", sa.Float, nullable=True),
        sa.Column("suppression_pct", sa.Float, nullable=True),
        sa.Column("stress_contribution_pct", sa.Float, nullable=True),
        sa.Column("suppression_area", sa.Float, nullable=False, server_default="0.0"),
        sa.Column("tag", sa.String(50), nullable=True),
        sa.Column("tag_candidate", sa.String(50), nullable=True),
        sa.Column("tag_source", sa.String(30), nullable=True, server_default="auto_detected"),
        sa.Column("nudge_sent", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("nudge_responded", sa.Boolean, nullable=False, server_default="false"),
    )
    op.create_index(
        "ix_stress_windows_user_start", "stress_windows", ["user_id", "started_at"]
    )

    # ── recovery_windows ──────────────────────────────────────────────────────
    op.create_table(
        "recovery_windows",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Float, nullable=False),
        sa.Column("context", sa.String(20), nullable=False, server_default="background"),
        sa.Column("rmssd_avg_ms", sa.Float, nullable=True),
        sa.Column("recovery_contribution_pct", sa.Float, nullable=True),
        sa.Column("recovery_area", sa.Float, nullable=False, server_default="0.0"),
        sa.Column("tag", sa.String(50), nullable=True),
        sa.Column("tag_source", sa.String(30), nullable=True),
        sa.Column(
            "zenflow_session_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("sessions.id", ondelete="SET NULL"),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_recovery_windows_user_start", "recovery_windows", ["user_id", "started_at"]
    )

    # ── tag_pattern_models ────────────────────────────────────────────────────
    op.create_table(
        "tag_pattern_models",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            unique=True,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer, nullable=True, server_default="1"),
        sa.Column("model_json", sa.JSON, nullable=False),
        sa.Column("sport_stressor_slugs", sa.JSON, nullable=True),
        sa.Column("patterns_built", sa.Integer, nullable=True, server_default="0"),
    )

    # ── daily_plans ───────────────────────────────────────────────────────────
    op.create_table(
        "daily_plans",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("plan_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("day_type", sa.String(10), nullable=True),
        sa.Column("readiness_score", sa.Float, nullable=True),
        sa.Column("stage", sa.Integer, nullable=True),
        sa.Column("items_json", sa.JSON, nullable=False),
        sa.Column("prescriber_notes", sa.JSON, nullable=True),
        sa.Column("adherence_pct", sa.Float, nullable=True),
    )
    op.create_index("ix_daily_plans_user_date", "daily_plans", ["user_id", "plan_date"])

    # ── plan_deviations ───────────────────────────────────────────────────────
    op.create_table(
        "plan_deviations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "plan_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("daily_plans.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "ts",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("activity_slug", sa.String(50), nullable=False),
        sa.Column("priority", sa.String(20), nullable=False),
        sa.Column("reason_category", sa.String(40), nullable=True),
        sa.Column("notes", sa.Text, nullable=True),
    )
    op.create_index("ix_plan_deviations_user_ts", "plan_deviations", ["user_id", "ts"])

    # ── daily_stress_summaries ────────────────────────────────────────────────
    op.create_table(
        "daily_stress_summaries",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("summary_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("wake_ts", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sleep_ts", sa.DateTime(timezone=True), nullable=True),
        sa.Column("wake_detection_method", sa.String(30), nullable=True),
        sa.Column("sleep_detection_method", sa.String(30), nullable=True),
        sa.Column("waking_minutes", sa.Float, nullable=True),
        sa.Column("stress_load_score", sa.Float, nullable=True),
        sa.Column("recovery_score", sa.Float, nullable=True),
        sa.Column("readiness_score", sa.Float, nullable=True),
        sa.Column("day_type", sa.String(10), nullable=True),
        sa.Column("raw_suppression_area", sa.Float, nullable=False, server_default="0.0"),
        sa.Column("raw_recovery_area_sleep", sa.Float, nullable=False, server_default="0.0"),
        sa.Column(
            "raw_recovery_area_zenflow", sa.Float, nullable=False, server_default="0.0"
        ),
        sa.Column(
            "raw_recovery_area_daytime", sa.Float, nullable=False, server_default="0.0"
        ),
        sa.Column(
            "max_possible_suppression", sa.Float, nullable=False, server_default="0.0"
        ),
        sa.Column("capacity_floor_used", sa.Float, nullable=True),
        sa.Column("capacity_version", sa.Integer, nullable=False, server_default="0"),
        sa.Column("calibration_days", sa.Integer, nullable=False, server_default="0"),
        sa.Column("is_estimated", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("is_partial_data", sa.Boolean, nullable=False, server_default="false"),
        sa.Column(
            "top_stress_window_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("stress_windows.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "top_recovery_window_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("recovery_windows.id", ondelete="SET NULL"),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_daily_summaries_user_date",
        "daily_stress_summaries",
        ["user_id", "summary_date"],
    )


def downgrade() -> None:
    # Drop in reverse dependency order
    op.drop_table("daily_stress_summaries")
    op.drop_table("plan_deviations")
    op.drop_table("daily_plans")
    op.drop_table("tag_pattern_models")
    op.drop_table("recovery_windows")
    op.drop_table("stress_windows")
    op.drop_table("background_windows")
    op.drop_table("monthly_outcomes")
    op.drop_table("weekly_outcomes")
    op.drop_table("conversation_events")
    op.drop_table("coach_messages")
    op.drop_table("check_ins")
    op.drop_table("morning_reads")
    op.drop_table("activity_coherence_events")
    op.drop_table("habit_events")
    op.drop_table("user_habits")
    op.drop_table("model_snapshots")
    op.drop_table("personal_models")
    op.drop_table("metrics")
    op.drop_table("sessions")
    op.drop_table("users")
