"""add_net_balance_waking_recovery_score

Revision ID: 957593d5ee14
Revises: 686e7a894f88
Create Date: 2026-03-14 09:01:16.771080+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957593d5ee14'
down_revision: Union[str, None] = '686e7a894f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_stress_summaries', sa.Column('waking_recovery_score', sa.Float(), nullable=True))
    op.add_column('daily_stress_summaries', sa.Column('net_balance', sa.Float(), nullable=True))
    op.add_column('daily_stress_summaries', sa.Column('raw_recovery_area_waking', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_stress_summaries', 'raw_recovery_area_waking')
    op.drop_column('daily_stress_summaries', 'net_balance')
    op.drop_column('daily_stress_summaries', 'waking_recovery_score')
    # ### end Alembic commands ###
