"""Add Tagging Models

Revision ID: ba281ccc3132
Revises: 0003
Create Date: 2026-03-12 16:43:14.990926+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba281ccc3132'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activity_coherence_events_user_id_fkey', 'activity_coherence_events', type_='foreignkey')
    op.create_foreign_key(None, 'activity_coherence_events', 'users', ['user_id'], ['id'])
    op.alter_column('anxiety_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('anxiety_events_user_id_fkey', 'anxiety_events', type_='foreignkey')
    op.drop_constraint('anxiety_events_stress_window_id_fkey', 'anxiety_events', type_='foreignkey')
    op.create_foreign_key(None, 'anxiety_events', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'anxiety_events', 'stress_windows', ['stress_window_id'], ['id'])
    op.drop_constraint('background_windows_user_id_fkey', 'background_windows', type_='foreignkey')
    op.create_foreign_key(None, 'background_windows', 'users', ['user_id'], ['id'])
    op.alter_column('check_ins', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('check_ins_user_id_fkey', 'check_ins', type_='foreignkey')
    op.create_foreign_key(None, 'check_ins', 'users', ['user_id'], ['id'])
    op.alter_column('coach_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('coach_messages_user_id_fkey', 'coach_messages', type_='foreignkey')
    op.create_foreign_key(None, 'coach_messages', 'users', ['user_id'], ['id'])
    op.alter_column('conversation_events', 'ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('conversation_events_user_id_fkey', 'conversation_events', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_events', 'users', ['user_id'], ['id'])
    op.alter_column('daily_plans', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('daily_plans_user_id_fkey', 'daily_plans', type_='foreignkey')
    op.create_foreign_key(None, 'daily_plans', 'users', ['user_id'], ['id'])
    op.alter_column('daily_stress_summaries', 'computed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('daily_stress_summaries_user_id_fkey', 'daily_stress_summaries', type_='foreignkey')
    op.drop_constraint('daily_stress_summaries_top_stress_window_id_fkey', 'daily_stress_summaries', type_='foreignkey')
    op.drop_constraint('daily_stress_summaries_top_recovery_window_id_fkey', 'daily_stress_summaries', type_='foreignkey')
    op.create_foreign_key(None, 'daily_stress_summaries', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'daily_stress_summaries', 'recovery_windows', ['top_recovery_window_id'], ['id'])
    op.create_foreign_key(None, 'daily_stress_summaries', 'stress_windows', ['top_stress_window_id'], ['id'])
    op.drop_constraint('habit_events_user_id_fkey', 'habit_events', type_='foreignkey')
    op.create_foreign_key(None, 'habit_events', 'users', ['user_id'], ['id'])
    op.drop_constraint('metrics_user_id_fkey', 'metrics', type_='foreignkey')
    op.drop_constraint('metrics_session_id_fkey', 'metrics', type_='foreignkey')
    op.create_foreign_key(None, 'metrics', 'sessions', ['session_id'], ['id'])
    op.create_foreign_key(None, 'metrics', 'users', ['user_id'], ['id'])
    op.alter_column('model_snapshots', 'snapshot_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('model_snapshots_user_id_fkey', 'model_snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'model_snapshots', 'users', ['user_id'], ['id'])
    op.alter_column('monthly_outcomes', 'computed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('monthly_outcomes_user_id_fkey', 'monthly_outcomes', type_='foreignkey')
    op.create_foreign_key(None, 'monthly_outcomes', 'users', ['user_id'], ['id'])
    op.alter_column('mood_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('mood_logs_user_id_fkey', 'mood_logs', type_='foreignkey')
    op.create_foreign_key(None, 'mood_logs', 'users', ['user_id'], ['id'])
    op.alter_column('morning_reads', 'captured_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('morning_reads_user_id_fkey', 'morning_reads', type_='foreignkey')
    op.create_foreign_key(None, 'morning_reads', 'users', ['user_id'], ['id'])
    op.alter_column('personal_models', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('personal_models_user_id_fkey', 'personal_models', type_='foreignkey')
    op.create_foreign_key(None, 'personal_models', 'users', ['user_id'], ['id'])
    op.alter_column('plan_deviations', 'ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('plan_deviations_plan_id_fkey', 'plan_deviations', type_='foreignkey')
    op.drop_constraint('plan_deviations_user_id_fkey', 'plan_deviations', type_='foreignkey')
    op.create_foreign_key(None, 'plan_deviations', 'daily_plans', ['plan_id'], ['id'])
    op.create_foreign_key(None, 'plan_deviations', 'users', ['user_id'], ['id'])
    op.drop_constraint('recovery_windows_user_id_fkey', 'recovery_windows', type_='foreignkey')
    op.drop_constraint('recovery_windows_zenflow_session_id_fkey', 'recovery_windows', type_='foreignkey')
    op.create_foreign_key(None, 'recovery_windows', 'sessions', ['zenflow_session_id'], ['id'])
    op.create_foreign_key(None, 'recovery_windows', 'users', ['user_id'], ['id'])
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('sessions_user_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint('stress_windows_user_id_fkey', 'stress_windows', type_='foreignkey')
    op.create_foreign_key(None, 'stress_windows', 'users', ['user_id'], ['id'])
    op.alter_column('tag_pattern_models', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('tag_pattern_models_user_id_fkey', 'tag_pattern_models', type_='foreignkey')
    op.create_foreign_key(None, 'tag_pattern_models', 'users', ['user_id'], ['id'])
    op.alter_column('user_facts', 'polarity',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'neutral'::character varying"))
    op.alter_column('user_facts', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0.5'::double precision"))
    op.drop_constraint('user_facts_user_id_fkey', 'user_facts', type_='foreignkey')
    op.create_foreign_key(None, 'user_facts', 'users', ['user_id'], ['id'])
    op.alter_column('user_habits', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('user_habits_user_id_fkey', 'user_habits', type_='foreignkey')
    op.create_foreign_key(None, 'user_habits', 'users', ['user_id'], ['id'])
    op.alter_column('user_psych_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('user_psych_profiles_user_id_fkey', 'user_psych_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_psych_profiles', 'users', ['user_id'], ['id'])
    op.alter_column('user_unified_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('user_unified_profiles_user_id_fkey', 'user_unified_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_unified_profiles', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('weekly_outcomes', 'computed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('weekly_outcomes_user_id_fkey', 'weekly_outcomes', type_='foreignkey')
    op.create_foreign_key(None, 'weekly_outcomes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weekly_outcomes', type_='foreignkey')
    op.create_foreign_key('weekly_outcomes_user_id_fkey', 'weekly_outcomes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('weekly_outcomes', 'computed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'user_unified_profiles', type_='foreignkey')
    op.create_foreign_key('user_unified_profiles_user_id_fkey', 'user_unified_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_unified_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'user_psych_profiles', type_='foreignkey')
    op.create_foreign_key('user_psych_profiles_user_id_fkey', 'user_psych_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_psych_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'user_habits', type_='foreignkey')
    op.create_foreign_key('user_habits_user_id_fkey', 'user_habits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_habits', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'user_facts', type_='foreignkey')
    op.create_foreign_key('user_facts_user_id_fkey', 'user_facts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_facts', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0.5'::double precision"))
    op.alter_column('user_facts', 'polarity',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'neutral'::character varying"))
    op.drop_constraint(None, 'tag_pattern_models', type_='foreignkey')
    op.create_foreign_key('tag_pattern_models_user_id_fkey', 'tag_pattern_models', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tag_pattern_models', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'stress_windows', type_='foreignkey')
    op.create_foreign_key('stress_windows_user_id_fkey', 'stress_windows', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_user_id_fkey', 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'recovery_windows', type_='foreignkey')
    op.drop_constraint(None, 'recovery_windows', type_='foreignkey')
    op.create_foreign_key('recovery_windows_zenflow_session_id_fkey', 'recovery_windows', 'sessions', ['zenflow_session_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('recovery_windows_user_id_fkey', 'recovery_windows', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'plan_deviations', type_='foreignkey')
    op.drop_constraint(None, 'plan_deviations', type_='foreignkey')
    op.create_foreign_key('plan_deviations_user_id_fkey', 'plan_deviations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('plan_deviations_plan_id_fkey', 'plan_deviations', 'daily_plans', ['plan_id'], ['id'], ondelete='CASCADE')
    op.alter_column('plan_deviations', 'ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'personal_models', type_='foreignkey')
    op.create_foreign_key('personal_models_user_id_fkey', 'personal_models', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('personal_models', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'morning_reads', type_='foreignkey')
    op.create_foreign_key('morning_reads_user_id_fkey', 'morning_reads', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('morning_reads', 'captured_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'mood_logs', type_='foreignkey')
    op.create_foreign_key('mood_logs_user_id_fkey', 'mood_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('mood_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'monthly_outcomes', type_='foreignkey')
    op.create_foreign_key('monthly_outcomes_user_id_fkey', 'monthly_outcomes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('monthly_outcomes', 'computed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'model_snapshots', type_='foreignkey')
    op.create_foreign_key('model_snapshots_user_id_fkey', 'model_snapshots', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('model_snapshots', 'snapshot_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'metrics', type_='foreignkey')
    op.drop_constraint(None, 'metrics', type_='foreignkey')
    op.create_foreign_key('metrics_session_id_fkey', 'metrics', 'sessions', ['session_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('metrics_user_id_fkey', 'metrics', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'habit_events', type_='foreignkey')
    op.create_foreign_key('habit_events_user_id_fkey', 'habit_events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'daily_stress_summaries', type_='foreignkey')
    op.drop_constraint(None, 'daily_stress_summaries', type_='foreignkey')
    op.drop_constraint(None, 'daily_stress_summaries', type_='foreignkey')
    op.create_foreign_key('daily_stress_summaries_top_recovery_window_id_fkey', 'daily_stress_summaries', 'recovery_windows', ['top_recovery_window_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('daily_stress_summaries_top_stress_window_id_fkey', 'daily_stress_summaries', 'stress_windows', ['top_stress_window_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('daily_stress_summaries_user_id_fkey', 'daily_stress_summaries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('daily_stress_summaries', 'computed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'daily_plans', type_='foreignkey')
    op.create_foreign_key('daily_plans_user_id_fkey', 'daily_plans', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('daily_plans', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'conversation_events', type_='foreignkey')
    op.create_foreign_key('conversation_events_user_id_fkey', 'conversation_events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('conversation_events', 'ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'coach_messages', type_='foreignkey')
    op.create_foreign_key('coach_messages_user_id_fkey', 'coach_messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('coach_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'check_ins', type_='foreignkey')
    op.create_foreign_key('check_ins_user_id_fkey', 'check_ins', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('check_ins', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'background_windows', type_='foreignkey')
    op.create_foreign_key('background_windows_user_id_fkey', 'background_windows', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'anxiety_events', type_='foreignkey')
    op.drop_constraint(None, 'anxiety_events', type_='foreignkey')
    op.create_foreign_key('anxiety_events_stress_window_id_fkey', 'anxiety_events', 'stress_windows', ['stress_window_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('anxiety_events_user_id_fkey', 'anxiety_events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('anxiety_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'activity_coherence_events', type_='foreignkey')
    op.create_foreign_key('activity_coherence_events_user_id_fkey', 'activity_coherence_events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
